Improve pretty printer for HsExpr
Given a very deeply-nested application, it just kept printing
deeper and deeper.  This small change makes it cut off.

Test is in #26330, but we also get a dramatic decrease in compile
time for perf/compiler/InstanceMatching:
   InstanceMatching  4,086,884,584  1,181,767,232 -71.1% GOOD
Why? Because before we got a GIGANTIC error message that took
ages to pretty-print; now we get this much more civilised message
(I have removed some whitespace.)

Match.hs:1007:1: error:
    • No instance for ‘Show (F001 a)’ arising from a use of ‘showsPrec’
    • In the second argument of ‘showString’, namely
        ‘(showsPrec
            11 b1
         (GHC.Internal.Show.showSpace
            (showsPrec
               11 b2
         (GHC.Internal.Show.showSpace
            (showsPrec
               11 b3
         (GHC.Internal.Show.showSpace
            (showsPrec
               11 b4
         (GHC.Internal.Show.showSpace
            (showsPrec
               11 b5
         (GHC.Internal.Show.showSpace
            (showsPrec
               11 b6
               (GHC.Internal.Show.showSpace (showsPrec ...)))))))))))))’

-----------------------
The main payload is

* At the start of `pprExpr`
* In the defn of `pprApp`

A little bit of refactoring:

* It turned out that we were setting the default cut-off depth to a
  fixed value in two places, so changing one didn't change the other.
  See defaultSDocDepth and defaultSDocCols

* I refactored `pprDeeperList` a bit so I could understand it better.

Because the depth calculation has changed, there are lots of small
error message wibbles.

Metric Decrease:
    InstanceMatching